services:
  discord-bot:
    build: .
    container_name: media-downloader-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Save downloads persistently in a hosted folder (in case OS cleanup skips a beat)
      - ./downloads:/app/downloads
